version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "06:00"
    timezone: "Asia/Tokyo"
    target_branch: "nyon"
  open-pull-requests-limit: 99
